### ISSUE TITLE
Issue with multiple line outputs since latest Arch/Systemd release

### ISSUE THREAD

**Issue by itsmontoya** [GoogleCloudPlatform/compute-archlinux-image-builder#8] opened 2015-08-04 21:50 UTC
There were some updates made public for the Linux Kernel and Systemd today. Ever since running said updates, anything which has multiple lines of output seem to crash the ssh connection. 

An easy example to replicate is running dmesg. 

I tested out the newest updates on my home server and everything worked great.

**Comment by OneOfOne** [comment] 2015-08-04 21:54
I can confirm this, on multiple different VM types (high-cpu-2 and normal-2).

The problem is a mix of `systemd-224` and `linux-4.1.4-1`.

**Comment by itsmontoya** [comment] 2015-08-04 21:57
To add to OneOfOne, my tests were on a small instance. So combined we have tested this on:
- Small
- High-Cpu-2
- Normal-2

**Comment by rfg** [comment] 2015-08-20 21:47
Reducing the mtu to 1440 on VM and local system resolved the issue.

http://serverfault.com/questions/96483/ssh-if-command-output-is-more-than-about-5-lines

https://code.google.com/p/google-compute-engine/issues/detail?id=127

**Comment by lcastelli** [comment] 2018-11-09 03:10
We just updated the project to a completely new implementation. Closing this issue as obsolete as it should not apply to the new version.

**Closed by lcastelli** 2018-11-09 03:10 UTC
